# Generated by Django 2.2 on 2020-10-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('father_mobile', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='', max_length=200)),
                ('address', models.TextField()),
                ('course', models.CharField(choices=[('fashion', 'fashion'), ('graphics', 'graphics'), ('fineart', 'fineart'), ('textile', 'textile'), ('jwellery', 'jwellery')], default='', max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('cpassword', models.CharField(max_length=100)),
                ('status', models.CharField(default='inactive', max_length=100)),
                ('registration_id', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=8)),
                ('join_date', models.DateField(max_length=8)),
                ('cast', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(default='', upload_to='images/')),
            ],
        ),
    ]
