# Generated by Django 2.2 on 2020-10-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_student_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_reg',
            name='batch',
            field=models.CharField(default='', max_length=100),
        ),
    ]
