# Generated by Django 2.2 on 2020-10-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_fees_detaile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees_detaile',
            name='recipt',
            field=models.FileField(default='', upload_to='recipt/'),
        ),
    ]
