# Generated by Django 2.2 on 2020-10-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_fees_detaile_recipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remaining_fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(max_length=100)),
                ('installment_no', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('payment_date', models.DateField(max_length=8)),
            ],
        ),
    ]
