# Generated by Django 2.2 on 2020-10-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_nm', models.CharField(max_length=100)),
                ('holiday_date', models.DateField(max_length=8)),
                ('holiday_day', models.CharField(max_length=100)),
                ('status', models.CharField(default='active', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default='kalaveethi Institute', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(max_length=8),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(),
        ),
    ]
