# Generated by Django 2.2 on 2020-10-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20201024_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(choices=[('fashion', 'fashion'), ('graphics', 'graphics'), ('fineart', 'fineart'), ('textile', 'textile'), ('jwellery', 'jwellery'), ('all', 'all')], default='', max_length=200)),
                ('notice_sub', models.CharField(max_length=100)),
                ('notice_date', models.DateField(max_length=8)),
                ('notice_desc', models.TextField()),
                ('status', models.CharField(default='active', max_length=100)),
            ],
        ),
    ]
