# Generated by Django 2.2 on 2020-10-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Createclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateField(max_length=8)),
                ('class_time', models.TimeField()),
                ('subject', models.CharField(max_length=100)),
                ('classtype', models.CharField(choices=[('lab', 'lab'), ('stitching', 'stitching'), ('theory', 'theory')], default='', max_length=200)),
                ('batch_nm', models.CharField(max_length=100)),
                ('organizer', models.CharField(max_length=100)),
                ('status', models.CharField(default='active', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice',
            field=models.CharField(choices=[('fashion', 'fashion'), ('graphics', 'graphics'), ('fineart', 'fineart'), ('textile', 'textile'), ('jwellery', 'jwellery'), ('all', 'all')], default='all', max_length=200),
        ),
    ]
