# Generated by Django 2.2 on 2020-10-25 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_studentleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentleave',
            name='leavedate',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
