# Generated by Django 2.2 on 2020-10-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_studentleave_leavedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleave',
            name='leavedate',
            field=models.DateField(max_length=8),
        ),
    ]
