# Generated by Django 2.2 on 2020-10-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20201025_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentLeave',
        ),
    ]
