# Generated by Django 2.2 on 2020-10-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_studentleave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentleave',
            old_name='course',
            new_name='subject_name',
        ),
        migrations.RenameField(
            model_name='studentleave',
            old_name='leavedate',
            new_name='submition_date',
        ),
        migrations.RenameField(
            model_name='studentleave',
            old_name='leave_day',
            new_name='topic',
        ),
        migrations.RemoveField(
            model_name='studentleave',
            name='Leave_catagory',
        ),
        migrations.RemoveField(
            model_name='studentleave',
            name='leave_reason',
        ),
        migrations.RemoveField(
            model_name='studentleave',
            name='registration_id',
        ),
        migrations.RemoveField(
            model_name='studentleave',
            name='sname',
        ),
        migrations.AddField(
            model_name='studentleave',
            name='submition_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentleave',
            name='submition_file',
            field=models.ImageField(default='', upload_to='student_submitions/'),
        ),
        migrations.AddField(
            model_name='studentleave',
            name='submitions',
            field=models.CharField(choices=[('fashion', 'fashion'), ('graphics', 'graphics'), ('fineart', 'fineart'), ('textile', 'textile'), ('jwellery', 'jwellery'), ('all', 'all')], default='all', max_length=200),
        ),
    ]
