# Generated by Django 2.2 on 2020-10-27 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20201027_1025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentLeave',
        ),
    ]
