# Generated by Django 2.2 on 2020-10-27 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_delete_studentleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(max_length=100)),
                ('sname', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('leavedate', models.DateField(default=datetime.datetime(2020, 10, 27, 10, 51, 45, 591476), max_length=8)),
                ('Leave_catagory', models.CharField(choices=[('Sick_Leave', 'Sick_Leave'), ('Extended_Sick', 'Extended_Sick'), ('Emergency_Leave', 'Emergency_Leave'), ('Long_Leave', 'Long_Leave')], default='', max_length=200)),
                ('leave_reason', models.CharField(max_length=100)),
                ('leave_day', models.CharField(max_length=100)),
                ('status', models.CharField(default='deactive', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubmitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitions', models.CharField(choices=[('fashion', 'fashion'), ('graphics', 'graphics'), ('fineart', 'fineart'), ('textile', 'textile'), ('jwellery', 'jwellery'), ('all', 'all')], default='all', max_length=200)),
                ('submition_name', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('submition_desc', models.TextField()),
                ('submition_date', models.DateField(default=datetime.datetime(2020, 10, 27, 10, 51, 45, 592476), max_length=8)),
                ('submition_file', models.FileField(default='', upload_to='student_submitions/')),
                ('status', models.CharField(default='deactive', max_length=100)),
            ],
        ),
    ]
