# Generated by Django 2.2 on 2020-10-27 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_studentleave_studentsubmitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleave',
            name='leavedate',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 10, 54, 44, 261216), max_length=8),
        ),
        migrations.AlterField(
            model_name='studentsubmitions',
            name='submition_date',
            field=models.DateField(max_length=8),
        ),
    ]
