# Generated by Django 2.2 on 2020-10-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20201027_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmitions',
            name='batch',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentleave',
            name='leavedate',
            field=models.DateField(default='', max_length=8),
        ),
    ]
