
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index,name='index'),
    path('admin_login/',views.admin_login,name='admin_login'),
    path('admin_dashboard/',views.admin_dashboard,name='admin_dashboard'),
    path('logout/',views.logout,name='logout'),
    path('Student_Registration/',views.Student_Registration,name='Student_Registration'),
    path('student_login/',views.student_login,name='student_login'),
    path('student_logout/',views.student_logout,name='student_logout'),
    path('View_Students/',views.View_Students,name='View_Students'),
    path('student_moreinfo/<int:pk>/',views.student_moreinfo,name='student_moreinfo'),
    path('delete_student/<int:pk>/',views.delete_student,name='delete_student'),
    path('student_profile/',views.student_profile,name='student_profile'),
    path('student_dashboard/',views.student_dashboard,name='student_dashboard'),
    path('student_change_password/',views.student_change_password,name='student_change_password'),
    path('edit_std_detail/<int:pk>',views.edit_std_detail,name='edit_std_detail'),
    path('student_inquiry',views.student_inquiry,name='student_inquiry'),
    path('student_inquiry_list/',views.student_inquiry_list,name='student_inquiry_list'),
    path('add_fees',views.add_fees,name='add_fees'),
    path('add_std_attendence/',views.add_std_attendence,name='add_std_attendence'),
    path('fill_attendence/',views.fill_attendence,name='fill_attendence'),
    path('add_fees/',views.add_fees,name='add_fees'),
    path('fees_details/',views.fees_details,name='fees_details'),
    path('sid_list/',views.sid_list,name='sid_list'),
    path('add_installment/',views.add_installment,name='add_installment'),
    path('add_fees_record/',views.add_fees_record,name='add_fees_record'),
    path('add_remaining_ins/',views.add_remaining_ins,name='add_remaining_ins'),
    path('insert_remeining_ins/',views.insert_remeining_ins,name='insert_remeining_ins'),
    path('event/',views.event,name='event'),
    path('insert_event/',views.insert_event,name='insert_event'),
    path('holiday/',views.holiday,name='holiday'),
    path('Submitions/',views.Submitions,name='Submitions'),
    path('notice/',views.notice,name='notice'),
    path('student_fees_detaile/',views.student_fees_detaile,name='student_fees_detaile'),
    path('student_notice_board/',views.student_notice_board,name='student_notice_board'),
    path('student_holiday/',views.student_holiday,name='student_holiday'),
    path('student_event/',views.student_event,name='student_event'),
    path('demo/',views.demo,name='demo'),
    path('student_attendence/',views.student_attendence,name='student_attendence'),
    path('pay_fees/',views.pay_fees,name='pay_fees'),
    path('student_class/',views.student_class,name='student_class'),
    path('student_submitions/',views.student_submitions,name='student_submitions'),
    path('student_leave/',views.student_leave,name='student_leave'),
    path('create_class/',views.create_class,name='create_class'),
    path('class_list/',views.class_list,name='class_list'),
    path('view_leave/',views.view_leave,name='view_leave'),
    path('approw_leavelist/',views.approw_leavelist,name='approw_leavelist'),
    path('reject_leavelist/',views.reject_leavelist,name='reject_leavelist'),
    path('approw_leave/',views.approw_leave,name='approw_leave'),
    path('reject_leave/',views.reject_leave,name='reject_leave'),
    path('leave_request_status/',views.leave_request_status,name='leave_request_status'),
    path('Insert_Suggestion/',views.Insert_Suggestion,name='Insert_Suggestion'),
    path('view_suggestion/',views.view_suggestion,name='view_suggestion'),
]
